# Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset

In [2]:
dataset = pd.read_csv("Position_Salaries.csv")
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [6]:
print(y)

[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


# Reshape data for SVR 

In [3]:
y = y.reshape(len(y), 1)

- Why I need to do this step, because StandardScaler only accepts 2-dimensional array, but the original y is just a 1-dimensional array, so you need to convert it.

---

- **``reshape(rows, columns)``** is a method in NumPy that changes the shape (dimensions) of an array without altering its data.



In [5]:
print(y)

[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


# Feature Scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_Y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_Y.fit_transform(y)

## Why Use Two Separate StandardScaler Objects?

The short answer: You use two separate StandardScaler objects because X and y are different variables with different distributions, and scaling them together with one scaler would mix their statistics (mean and standard deviation), leading to incorrect scaling.

### Different Ranges and Distributions

- **X (Level)**: Values range from 1 to 10
    - This is a small range, and the values are fairly evenly spaced (1, 2, 3, ..., 10)
    
- **y (Salary)**: Values range from 45,000 to 1,000,000
    - This is a massive range, and the values grow exponentially (e.g., salaries jump from 45,000 to 200,000 to 1,000,000)

### How StandardScaler Works

StandardScaler standardizes data by:
1. Subtracting the mean (average value) of the data
2. Dividing by the standard deviation 

### An example in this case
- The mean of X (1 to 10) might be around 5.5, with a small standard deviation.
- The mean of y (45,000 to 10,000,000) might be around 1,000,000, with a huge standard deviation.

In [7]:
print(X)

[[-1.5666989 ]
 [-1.21854359]
 [-0.87038828]
 [-0.52223297]
 [-0.17407766]
 [ 0.17407766]
 [ 0.52223297]
 [ 0.87038828]
 [ 1.21854359]
 [ 1.5666989 ]]


In [8]:
print(y)

[[-0.72004253]
 [-0.70243757]
 [-0.66722767]
 [-0.59680786]
 [-0.49117815]
 [-0.35033854]
 [-0.17428902]
 [ 0.17781001]
 [ 0.88200808]
 [ 2.64250325]]


# Training the SVR model on the whole dataset

In [5]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(X,y)

/media/thdong07/Private/UDEMY/Machine Learning/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

### Explain about the abonve code


**kernel** is a function that

- can either learn linear relationships (**linear kernel**)
- or learn non-linear relationships (**non-linear kernel**)

--- 

``rbf``: Radial basis function

# Predicting a new result

In [ ]:
sc_Y.inverse_transform(regressor.predict(sc_X.transform([[6.5]])).reshape(1,-1))

[-0.27861589]


### Explain about the above code
- **``inverse_transform()``**: Scale back the data to the original scale
    - Example: Assume the original scale is $75000 and the scaled version is 0.75. This function will convert 0.75 to $75000
    
- **``transform()``**: Convert original scale to the scaled version
    - Example: Reverse version of **``inverse_transform()``**

- **``reshape(1,-1)``**: Changes the shape (structure) of the data into a 2D array with 1 row and an automatically determined number of columns.
    - Example: [0.75] -> [[0.75]]

