## Importing the libraries

In [1]:
import pandas as pd
import numpy as np

## Import the dataset

In [3]:
df = pd.read_csv('Salary_Data.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [4]:
print(X)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


In [5]:
print(y)

[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]


## Spliting the dataset to training set and test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)

In [ ]:
print(X_train)

[[ 9.6]
 [ 4. ]
 [ 5.3]
 [ 7.9]
 [ 2.9]
 [ 5.1]
 [ 3.2]
 [ 4.5]
 [ 8.2]
 [ 6.8]
 [ 1.3]
 [10.5]
 [ 3. ]
 [ 2.2]
 [ 5.9]
 [ 6. ]
 [ 3.7]
 [ 3.2]
 [ 9. ]
 [ 2. ]
 [ 1.1]
 [ 7.1]
 [ 4.9]
 [ 4. ]]


In [9]:
print(X_test)

[[ 1.5]
 [10.3]
 [ 4.1]
 [ 3.9]
 [ 9.5]
 [ 8.7]]


In [11]:
print(y_train)

[112635.  55794.  83088. 101302.  56642.  66029.  64445.  61111. 113812.
  91738.  46205. 121872.  60150.  39891.  81363.  93940.  57189.  54445.
 105582.  43525.  39343.  98273.  67938.  56957.]


In [12]:
print(y_test)

[ 37731. 122391.  57081.  63218. 116969. 109431.]


## Why we don't have: Encoding and Taking care of missing data

* This is because our dataset is perfect that doesn't contain any "object" types and also doesn't miss any data

## Training the Simple linear regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

### LinearRegression from scikit-learn is used to model the relationship between one or more independent variables (features) and a continuous dependent variable (target). Here’s how you typically use it:

1. Instantiate the LinearRegression model.
2. Fit the model on the training data using the fit() method.
3. Use the predict() method to make predictions on new data (e.g., the test set).

For example, if you have already split your dataset into X_train, X_test, y_train, and y_test, you can do the following:


Assuming regressor is already defined as:
from sklearn.linear_model import LinearRegression
 regressor = LinearRegression()

* Fit the model on the training set
```
regressor.fit(X_train, y_train)
```

* Predict on the test set
```
y_pred = regressor.predict(X_test)
```

* Print predictions
```
print("Predictions:", y_pred)
```